"""baseline: full schema as of 2026-07-19

Revision ID: c8a93dfde825
Revises: 
Create Date: 2026-07-18 23:42:07.318128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8a93dfde825'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chain_scan_checkpoints',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('last_scanned_block', sa.Integer(), nullable=False),
    sa.Column('is_backfilled', sa.Boolean(), nullable=False),
    sa.Column('pre_ledger_baseline_cents', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chain_checkpoint_wallet_chain', 'chain_scan_checkpoints', ['wallet_address', 'chain'], unique=True)
    op.create_index(op.f('ix_chain_scan_checkpoints_wallet_address'), 'chain_scan_checkpoints', ['wallet_address'], unique=False)
    op.create_table('deal_suggestions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('school', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('suggestion', sa.String(), nullable=False),
    sa.Column('submitter_email', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deal_suggestions_school'), 'deal_suggestions', ['school'], unique=False)
    op.create_index(op.f('ix_deal_suggestions_status'), 'deal_suggestions', ['status'], unique=False)
    op.create_table('email_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('email_number', sa.Integer(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_email'), 'email_log', ['email'], unique=False)
    op.create_table('fee_collections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('collection_date', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('total_fees_cents', sa.Integer(), nullable=False),
    sa.Column('transfer_count', sa.Integer(), nullable=False),
    sa.Column('treasury_wallet', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_collections_collection_date'), 'fee_collections', ['collection_date'], unique=False)
    op.create_table('founding_members',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('member_number', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(), nullable=True),
    sa.Column('stripe_session_id', sa.String(), nullable=True),
    sa.Column('referral_code_used', sa.String(), nullable=True),
    sa.Column('refunded', sa.Boolean(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_session_id')
    )
    op.create_index(op.f('ix_founding_members_email'), 'founding_members', ['email'], unique=False)
    op.create_index(op.f('ix_founding_members_member_number'), 'founding_members', ['member_number'], unique=False)
    op.create_table('gas_station_topups',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('amount_wei', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gas_station_topups_chain'), 'gas_station_topups', ['chain'], unique=False)
    op.create_index(op.f('ix_gas_station_topups_created_at'), 'gas_station_topups', ['created_at'], unique=False)
    op.create_index(op.f('ix_gas_station_topups_wallet_address'), 'gas_station_topups', ['wallet_address'], unique=False)
    op.create_table('handles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('handle', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handles_handle'), 'handles', ['handle'], unique=True)
    op.create_index(op.f('ix_handles_user_id'), 'handles', ['user_id'], unique=True)
    op.create_table('investing_orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('alpaca_order_id', sa.String(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('notional_cents', sa.Integer(), nullable=True),
    sa.Column('qty', sa.Numeric(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investing_orders_alpaca_order_id'), 'investing_orders', ['alpaca_order_id'], unique=True)
    op.create_index(op.f('ix_investing_orders_idempotency_key'), 'investing_orders', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_investing_orders_status'), 'investing_orders', ['status'], unique=False)
    op.create_index(op.f('ix_investing_orders_user_id'), 'investing_orders', ['user_id'], unique=False)
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_email'), 'magic_link_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token_hash'), 'magic_link_tokens', ['token_hash'], unique=True)
    op.create_table('news_alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_alerts_user_id'), 'news_alerts', ['user_id'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_table('plaid_items',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('account_mask', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plaid_items_item_id'), 'plaid_items', ['item_id'], unique=True)
    op.create_index(op.f('ix_plaid_items_status'), 'plaid_items', ['status'], unique=False)
    op.create_index(op.f('ix_plaid_items_user_id'), 'plaid_items', ['user_id'], unique=False)
    op.create_table('podcast_episodes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('episode_date', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('script', sa.String(), nullable=False),
    sa.Column('audio_mp3', sa.LargeBinary(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('est_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('source_headline_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_podcast_episodes_episode_date'), 'podcast_episodes', ['episode_date'], unique=True)
    op.create_table('sanctioned_addresses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('currency_label', sa.String(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctioned_addresses_address'), 'sanctioned_addresses', ['address'], unique=True)
    op.create_table('sanctions_list_refreshes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('addresses_found', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sanctions_list_refreshes_created_at'), 'sanctions_list_refreshes', ['created_at'], unique=False)
    op.create_table('stripe_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('is_student', sa.Boolean(), nullable=True),
    sa.Column('school', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('military_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('crypto_wallet_address', sa.String(), nullable=True),
    sa.Column('wallet_type', sa.String(), nullable=True),
    sa.Column('usdc_balance_cents', sa.Integer(), nullable=False),
    sa.Column('wallet_initialized', sa.Boolean(), nullable=False),
    sa.Column('total_fees_paid_cents', sa.Integer(), nullable=False),
    sa.Column('alpaca_account_id', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('referred_by', sa.String(), nullable=True),
    sa.Column('referral_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_crypto_wallet_address'), 'users', ['crypto_wallet_address'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_referral_code'), 'users', ['referral_code'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('waitlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('referral_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_email'), 'waitlist', ['email'], unique=True)
    op.create_table('bank_transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_name', sa.String(), nullable=False),
    sa.Column('recipient_routing_number', sa.String(), nullable=False),
    sa.Column('recipient_account_last4', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('ach_id', sa.String(), nullable=True),
    sa.Column('stripe_payout_id', sa.String(), nullable=True),
    sa.Column('stripe_payout_status', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed')"),
    sa.CheckConstraint('amount_cents > 0'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bank_transfer_pending', 'bank_transfers', ['sender_id', 'status'], unique=False)
    op.create_index('idx_bank_transfer_sender_created', 'bank_transfers', ['sender_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_bank_transfers_ach_id'), 'bank_transfers', ['ach_id'], unique=True)
    op.create_index(op.f('ix_bank_transfers_created_at'), 'bank_transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_bank_transfers_idempotency_key'), 'bank_transfers', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_bank_transfers_sender_id'), 'bank_transfers', ['sender_id'], unique=False)
    op.create_index(op.f('ix_bank_transfers_status'), 'bank_transfers', ['status'], unique=False)
    op.create_index(op.f('ix_bank_transfers_stripe_payout_id'), 'bank_transfers', ['stripe_payout_id'], unique=True)
    op.create_table('crypto_deposits',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('contract_address', sa.String(), nullable=False),
    sa.Column('from_address', sa.String(), nullable=False),
    sa.Column('to_address', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=False),
    sa.Column('credited_to_ledger', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint('amount_cents > 0'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crypto_deposit_dedupe', 'crypto_deposits', ['chain', 'tx_hash', 'contract_address', 'to_address'], unique=True)
    op.create_index('idx_crypto_deposit_user_created', 'crypto_deposits', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_crypto_deposits_created_at'), 'crypto_deposits', ['created_at'], unique=False)
    op.create_index(op.f('ix_crypto_deposits_to_address'), 'crypto_deposits', ['to_address'], unique=False)
    op.create_index(op.f('ix_crypto_deposits_tx_hash'), 'crypto_deposits', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_crypto_deposits_user_id'), 'crypto_deposits', ['user_id'], unique=False)
    op.create_table('crypto_trades',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('from_token', sa.String(), nullable=False),
    sa.Column('to_token', sa.String(), nullable=False),
    sa.Column('from_amount_cents', sa.Integer(), nullable=False),
    sa.Column('to_amount_cents', sa.Integer(), nullable=True),
    sa.Column('expected_to_amount_cents', sa.Integer(), nullable=False),
    sa.Column('price_per_unit', sa.String(), nullable=False),
    sa.Column('slippage_tolerance_percent', sa.String(), nullable=False),
    sa.Column('slippage_applied_percent', sa.String(), nullable=True),
    sa.Column('platform_fee_cents', sa.Integer(), nullable=False),
    sa.Column('gas_estimate_cents', sa.Integer(), nullable=True),
    sa.Column('actual_gas_used_cents', sa.Integer(), nullable=True),
    sa.Column('total_cost_cents', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('value_now_cents', sa.Integer(), nullable=True),
    sa.Column('gain_loss_cents', sa.Integer(), nullable=True),
    sa.Column('gain_loss_percent', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('quote', 'pending', 'completed', 'failed', 'cancelled')"),
    sa.CheckConstraint('expected_to_amount_cents > 0'),
    sa.CheckConstraint('from_amount_cents > 0'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crypto_trade_pending', 'crypto_trades', ['status', 'created_at'], unique=False)
    op.create_index('idx_crypto_trade_user_created', 'crypto_trades', ['user_id', 'created_at'], unique=False)
    op.create_index('idx_crypto_trade_user_status', 'crypto_trades', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_crypto_trades_created_at'), 'crypto_trades', ['created_at'], unique=False)
    op.create_index(op.f('ix_crypto_trades_idempotency_key'), 'crypto_trades', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_crypto_trades_status'), 'crypto_trades', ['status'], unique=False)
    op.create_index(op.f('ix_crypto_trades_tx_hash'), 'crypto_trades', ['tx_hash'], unique=True)
    op.create_index(op.f('ix_crypto_trades_user_id'), 'crypto_trades', ['user_id'], unique=False)
    op.create_table('crypto_transfers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('sender_id', sa.String(), nullable=False),
    sa.Column('recipient_address', sa.String(), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('fee_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('tx_hash', sa.String(), nullable=True),
    sa.Column('chain', sa.String(), nullable=True),
    sa.Column('memo', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'completed', 'failed', 'pending_review', 'approving', 'rejected')", name='ck_crypto_transfers_status'),
    sa.CheckConstraint('amount_cents > 0'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crypto_transfer_pending', 'crypto_transfers', ['sender_id', 'status'], unique=False)
    op.create_index('idx_crypto_transfer_recipient_date', 'crypto_transfers', ['recipient_address', 'created_at'], unique=False)
    op.create_index('idx_crypto_transfer_sender_created', 'crypto_transfers', ['sender_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_crypto_transfers_created_at'), 'crypto_transfers', ['created_at'], unique=False)
    op.create_index(op.f('ix_crypto_transfers_recipient_address'), 'crypto_transfers', ['recipient_address'], unique=False)
    op.create_index(op.f('ix_crypto_transfers_sender_id'), 'crypto_transfers', ['sender_id'], unique=False)
    op.create_index(op.f('ix_crypto_transfers_status'), 'crypto_transfers', ['status'], unique=False)
    op.create_table('crypto_wallets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('wallet_address', sa.String(), nullable=False),
    sa.Column('wallet_type', sa.String(), nullable=False),
    sa.Column('chain', sa.String(), nullable=False),
    sa.Column('usdc_balance_cents', sa.Integer(), nullable=False),
    sa.Column('encrypted_private_key', sa.LargeBinary(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("chain IN ('polygon', 'ethereum')"),
    sa.CheckConstraint("wallet_type IN ('non_custodial', 'fawn_custodial')"),
    sa.CheckConstraint('usdc_balance_cents >= 0'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_crypto_wallet_user_chain', 'crypto_wallets', ['user_id', 'chain'], unique=False)
    op.create_index(op.f('ix_crypto_wallets_user_id'), 'crypto_wallets', ['user_id'], unique=True)
    op.create_index(op.f('ix_crypto_wallets_wallet_address'), 'crypto_wallets', ['wallet_address'], unique=True)
    op.create_table('investing_watchlist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_watchlist_user_symbol', 'investing_watchlist', ['user_id', 'symbol'], unique=True)
    op.create_index(op.f('ix_investing_watchlist_user_id'), 'investing_watchlist', ['user_id'], unique=False)
    op.create_table('user_audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('details', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('retention_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_log_user_date', 'user_audit_log', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_audit_log_action'), 'user_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_user_audit_log_created_at'), 'user_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_audit_log_retention_expires_at'), 'user_audit_log', ['retention_expires_at'], unique=False)
    op.create_index(op.f('ix_user_audit_log_user_id'), 'user_audit_log', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_audit_log_user_id'), table_name='user_audit_log')
    op.drop_index(op.f('ix_user_audit_log_retention_expires_at'), table_name='user_audit_log')
    op.drop_index(op.f('ix_user_audit_log_created_at'), table_name='user_audit_log')
    op.drop_index(op.f('ix_user_audit_log_action'), table_name='user_audit_log')
    op.drop_index('idx_audit_log_user_date', table_name='user_audit_log')
    op.drop_table('user_audit_log')
    op.drop_index(op.f('ix_investing_watchlist_user_id'), table_name='investing_watchlist')
    op.drop_index('idx_watchlist_user_symbol', table_name='investing_watchlist')
    op.drop_table('investing_watchlist')
    op.drop_index(op.f('ix_crypto_wallets_wallet_address'), table_name='crypto_wallets')
    op.drop_index(op.f('ix_crypto_wallets_user_id'), table_name='crypto_wallets')
    op.drop_index('idx_crypto_wallet_user_chain', table_name='crypto_wallets')
    op.drop_table('crypto_wallets')
    op.drop_index(op.f('ix_crypto_transfers_status'), table_name='crypto_transfers')
    op.drop_index(op.f('ix_crypto_transfers_sender_id'), table_name='crypto_transfers')
    op.drop_index(op.f('ix_crypto_transfers_recipient_address'), table_name='crypto_transfers')
    op.drop_index(op.f('ix_crypto_transfers_created_at'), table_name='crypto_transfers')
    op.drop_index('idx_crypto_transfer_sender_created', table_name='crypto_transfers')
    op.drop_index('idx_crypto_transfer_recipient_date', table_name='crypto_transfers')
    op.drop_index('idx_crypto_transfer_pending', table_name='crypto_transfers')
    op.drop_table('crypto_transfers')
    op.drop_index(op.f('ix_crypto_trades_user_id'), table_name='crypto_trades')
    op.drop_index(op.f('ix_crypto_trades_tx_hash'), table_name='crypto_trades')
    op.drop_index(op.f('ix_crypto_trades_status'), table_name='crypto_trades')
    op.drop_index(op.f('ix_crypto_trades_idempotency_key'), table_name='crypto_trades')
    op.drop_index(op.f('ix_crypto_trades_created_at'), table_name='crypto_trades')
    op.drop_index('idx_crypto_trade_user_status', table_name='crypto_trades')
    op.drop_index('idx_crypto_trade_user_created', table_name='crypto_trades')
    op.drop_index('idx_crypto_trade_pending', table_name='crypto_trades')
    op.drop_table('crypto_trades')
    op.drop_index(op.f('ix_crypto_deposits_user_id'), table_name='crypto_deposits')
    op.drop_index(op.f('ix_crypto_deposits_tx_hash'), table_name='crypto_deposits')
    op.drop_index(op.f('ix_crypto_deposits_to_address'), table_name='crypto_deposits')
    op.drop_index(op.f('ix_crypto_deposits_created_at'), table_name='crypto_deposits')
    op.drop_index('idx_crypto_deposit_user_created', table_name='crypto_deposits')
    op.drop_index('idx_crypto_deposit_dedupe', table_name='crypto_deposits')
    op.drop_table('crypto_deposits')
    op.drop_index(op.f('ix_bank_transfers_stripe_payout_id'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_status'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_sender_id'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_idempotency_key'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_created_at'), table_name='bank_transfers')
    op.drop_index(op.f('ix_bank_transfers_ach_id'), table_name='bank_transfers')
    op.drop_index('idx_bank_transfer_sender_created', table_name='bank_transfers')
    op.drop_index('idx_bank_transfer_pending', table_name='bank_transfers')
    op.drop_table('bank_transfers')
    op.drop_index(op.f('ix_waitlist_email'), table_name='waitlist')
    op.drop_table('waitlist')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_referral_code'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_crypto_wallet_address'), table_name='users')
    op.drop_table('users')
    op.drop_table('stripe_events')
    op.drop_index(op.f('ix_sanctions_list_refreshes_created_at'), table_name='sanctions_list_refreshes')
    op.drop_table('sanctions_list_refreshes')
    op.drop_index(op.f('ix_sanctioned_addresses_address'), table_name='sanctioned_addresses')
    op.drop_table('sanctioned_addresses')
    op.drop_index(op.f('ix_podcast_episodes_episode_date'), table_name='podcast_episodes')
    op.drop_table('podcast_episodes')
    op.drop_index(op.f('ix_plaid_items_user_id'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_status'), table_name='plaid_items')
    op.drop_index(op.f('ix_plaid_items_item_id'), table_name='plaid_items')
    op.drop_table('plaid_items')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_news_alerts_user_id'), table_name='news_alerts')
    op.drop_table('news_alerts')
    op.drop_index(op.f('ix_magic_link_tokens_token_hash'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_email'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_index(op.f('ix_investing_orders_user_id'), table_name='investing_orders')
    op.drop_index(op.f('ix_investing_orders_status'), table_name='investing_orders')
    op.drop_index(op.f('ix_investing_orders_idempotency_key'), table_name='investing_orders')
    op.drop_index(op.f('ix_investing_orders_alpaca_order_id'), table_name='investing_orders')
    op.drop_table('investing_orders')
    op.drop_index(op.f('ix_handles_user_id'), table_name='handles')
    op.drop_index(op.f('ix_handles_handle'), table_name='handles')
    op.drop_table('handles')
    op.drop_index(op.f('ix_gas_station_topups_wallet_address'), table_name='gas_station_topups')
    op.drop_index(op.f('ix_gas_station_topups_created_at'), table_name='gas_station_topups')
    op.drop_index(op.f('ix_gas_station_topups_chain'), table_name='gas_station_topups')
    op.drop_table('gas_station_topups')
    op.drop_index(op.f('ix_founding_members_member_number'), table_name='founding_members')
    op.drop_index(op.f('ix_founding_members_email'), table_name='founding_members')
    op.drop_table('founding_members')
    op.drop_index(op.f('ix_fee_collections_collection_date'), table_name='fee_collections')
    op.drop_table('fee_collections')
    op.drop_index(op.f('ix_email_log_email'), table_name='email_log')
    op.drop_table('email_log')
    op.drop_index(op.f('ix_deal_suggestions_status'), table_name='deal_suggestions')
    op.drop_index(op.f('ix_deal_suggestions_school'), table_name='deal_suggestions')
    op.drop_table('deal_suggestions')
    op.drop_index(op.f('ix_chain_scan_checkpoints_wallet_address'), table_name='chain_scan_checkpoints')
    op.drop_index('idx_chain_checkpoint_wallet_chain', table_name='chain_scan_checkpoints')
    op.drop_table('chain_scan_checkpoints')
    # ### end Alembic commands ###
